const dealStatus = {
  WAIT_RESPONSE: 'WAIT_RESPONSE',
  WAIT_PAYMENT: 'WAIT_PAYMENT',
  WAIT_RECEIVING: 'WAIT_RECEIVING',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
}

module.exports = { dealStatus }
